$(document).ready(function(){
	$(".doc,.app,.disp,.info,.grav,#accion-group:not(.logo)").css("opacity","0");
	$(".icon").css("opacity","0.9");
	$(".grav.icon").css("opacity","1");
	$(".btn.act").hover(function(){	
			$(".doc,.app,.disp").css("opacity","1");
		},function(){
			$(".doc,.app,.disp").css("opacity","0");
			$(".icon:not(.grav)").css("opacity","0.9");
	});
	$(".btn.acc").hover(function(){
			$("#accion-group").css("opacity","1");
			$("#accion-group.logo").css("opacity","0");
		},function(){
			$("#accion-group").css("opacity","0");
			$("#accion-group.logo").css("opacity","1");
	});
	$(".btn.pol").hover(function(){
			$(".info,.grav").css("opacity","1");
			$(".grav.icon").attr("src","img/grav-icon2.png");
		},function(){
			$(".info,.grav:not(.icon)").css("opacity","0");
			$(".grav.icon").attr("src","img/grav-icon.png");
			$(".icon:not(.grav)").css("opacity","0.9");
	});
	$(".icon.doc").hover(function(){
			$(".doc").css("opacity","1");
		},function(){
			$(".doc").css("opacity","0");
			$(".icon:not(.grav)").css("opacity","0.9");
	});
	$(".icon.app").hover(function(){
			$(".app").css("opacity","1");
		},function(){
			$(".app").css("opacity","0");
			$(".icon:not(.grav)").css("opacity","0.9");
	});
	$(".icon.disp").hover(function(){
			$(".disp").css("opacity","1");
		},function(){
			$(".disp").css("opacity","0");
			$(".icon:not(.grav)").css("opacity","0.9");
	});
	$(".icon.info").hover(function(){
			$(".info").css("opacity","1");
		},function(){
			$(".info").css("opacity","0");
			$(".icon:not(.grav)").css("opacity","0.9");
	});
	$(".icon.grav").hover(function(){
			$(this).attr("src","img/grav-icon2.png");
			$(".grav").css("opacity","1");
			
		},function(){
			$(this).attr("src","img/grav-icon.png");
			$(".grav:not(.icon)").css("opacity","0");
			$(".icon:not(.grav)").css("opacity","0.9");
	});
});